### PR TITLE
Update Elastic.php & Documentation

### PR DESCRIPTION
**Pull request by ottar-eten-yod**
Fix Elastic Search's depreciations and update PHP coding standard to 8.1.

Fixes issue #45 
@harisnaeemofficial

### CODE REVIEW

**Comment by ivan1986** [comment]
when erver will migrate to 8.x
now 7.17.1

**Comment by ottar-eten-yod** [comment]
You are going to migrate the Elasticserver to 8.x from 7.17.1?

**Comment by ivan1986** [comment]
when will be a free time and i move to my server - i need get new oracle cloud account, but for this i need credit card, and for this i need go away from fucking russia

**Comment by ottar-eten-yod** [comment]
@ivan1986 If you want, I can give you access to a VPS if you need to work on development?

**Comment by ivan1986** [comment]
now it's work, and all looks good, only elastic not last version, but may update
it's free non profit project and i try use free servers, was from aws, then google, then oracle
I do not want to strain anyone with payment by the server, and main issue - free time now :)

but if you want i may setup it on your server and switch part of traffic

**Comment by ottar-eten-yod** [comment]
Do you have a Discord or something so details can be sent across. It will be an Oracle Cloud machine if that works?

And yeah, I mean I will try and help develop I will just need to learn your code etc.

**Comment by ivan1986** [comment]
Ivan1986#7040

yep, one small oracle instance works, but now it has LA about 10-15 and i can not update, because i banned

**Pull request merged**
